/* eslint-disable no-unused-vars */
export enum ActionConstants {
  TOGGLE_LOADING = 'TOGGLE_LOADING',
  GET_CRYPTO_LIST = 'GET_CRYPTO_LIST',
  SET_CRYPTO_LIST = 'SET_CRYPTO_LIST',
  SET_CRYPTO_BY_ID = 'SET_CRYPTO_BY_ID',
  GET_CRYPTO_BY_ID = 'GET_CRYPTO_BY_ID',
  GET_CRYPTO_PAGINATION = 'GET_CRYPTO_PAGINATION',
  SET_CRYPTO_LIST_PAGINATION = 'SET_CRYPTO_LIST_PAGINATION',
  GET_CRYPTO_HISTORY_BY_ID = 'GET_CRYPTO_HISTORY_BY_ID',
  SET_CRYPTO_HISTORY_BY_ID = 'SET_CRYPTO_HISTORY_BY_ID',
  GET_CRYPTO_FULL_INFO = 'GET_CRYPTO_FULL_INFO',
}