export enum ActionConstants {
  TOGGLE_LOADING = 'TOGGLE_LOADING',
  GET_CRYPTO_LIST = 'GET_CRYPTO_LIST',
  SET_CRYPTO_LIST = 'SET_CRYPTO_LIST',
  SET_CRYPTO_BY_ID = 'SET_CRYPTO_BY_ID',
  GET_CRYPTO_BY_ID = 'GET_CRYPTO_BY_ID',
}